### ISSUE TITLE
help

### ISSUE THREAD

**Issue by griffin-k** [caronero/Zero-Rat#1]
how you decrypt airavat rat script.js file

**Comment by caronero** [comment]
I could not decrypted but i remove it and put my own code

**Comment by karimullah0** [comment]
grt but in your code many thigs missing like tourch browser etc
can you chng this payload to another apk ?

**Comment by karimullah0** [comment]
broh why you are not updateing this add some new feture

**Comment by ChillVibesMushroom** [comment]
the google app id is which one bro lul the mobile sdk app id

**Comment by caronero** [comment]
guys it is up to you now add updates to the tool , i don't have time to keep it updated
